### ISSUE TITLE
Getting an error when running python cli.py

### ISSUE THREAD

**Issue by cfbauer** [luketurner/fitocracy-export#2]
Thanks for the code. Unfortunately I'm getting the following error:

`Traceback (most recent call last):`

  `File "cli.py", line 3, in <module> from fitocracy_export import *`

  `File "/home/chris/Documents/Fitocracy/fitocracy-export2/fitocracy-export/fitocracy_export/__init__.py", line 4, in <module> from http.cookiejar import CookieJar`

`ImportError: No module named http.cookiejar`

I'm on Ubuntu Gnome 15.10.

**Comment by luketurner** [comment]
The `http.cookiejar` is part of the Python 3 standard library, so I suspect this is because you are using Python 2. I'll update the README to indicate the Python 3 dependency. Thanks!

**Comment by luketurner** [comment]
Fixed. Considering your problem is 1.5 years old at this point, I'm closing this issue. Feel free to reopen it if things still don't work for you.
